# Header

menu:
  主页: /
  归档: /archives

# SubNav
subnav:
  blog: "https://bujige.net"         # blog 
  github: "#"                        # GitHub
  weibo: "#"                         # 微博
  rss: "#"                           # rss
#  zhihu: "#"                         # 知乎
#  csdn: "#"                          # CSDN
#  cnblogs: "#"                       # 博客园
#  gitee: "#"                         # 码云
#  qq: "#"                            # QQ
#  weixin: "/img/weixin.png"          # 微信
#  jianshu: "#"                       # 简书
#  douban: "#"                        # 豆瓣
#  segmentfault: "#"                  # 思否
#  bilibili: "#"                      # 哔哩哔哩
#  acfun: "#"                         # AcFun
#  mail: "mailto:xxxxx@xx.com"        # mail
#  facebook: "#"                      # Facebook
#  google: "#"                        # Google
#  twitter: "#"                       # Twitter
#  linkedin: "#"                      # LinkedIn

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章卡片右下角常驻链接，不需要请设置为 false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏; 1-文章对应的.md文件里有 reward:true 属性，才有打赏; 2-所有文章均有打赏.
reward_type: 2
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# 目录
# 目录设定：0-不显示目录; 1-文章对应的.md文件里有 toc:true 属性，才有目录; 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为 true 即可隐藏 hexo 重复的序号；否则置为 false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''

# 网站图标 url
favicon: /favicon.png

# 你的头像 url
avatar:

# 是否开启分享
share_jia: true

# 评论：1. 畅言; 2. Disqus; 3. Gitment; 4. Giteement
# 不需要使用某项，直接设置值为 false，或注释掉。
# 具体请参考 wiki：https://github.com/litten/hexo-theme-yilia/wiki/

# 1. 畅言
changyan_appid: false
changyan_conf: false

# 2. Disqus：在 hexo 根目录的 config 里也有 disqus_shortname 字段，优先使用 Yulia 的
disqus: false

# 3. Gitment
gitment_owner: false        # 你的 GitHub ID
gitment_accelerate: true    # 是否使用自定义 js 提升访问速度（置为 true 则使用本地 js 加速，置为 false 则使用官网默认 js）
gitment_repo: ''            # 存储评论的 repo
gitment_oauth:
  client_id: ''             # client ID
  client_secret: ''         # client secret

# 4. Giteement


# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider 的设置
slider:
  # 是否默认展开 tags 板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为 false
# 比如
# smart_menu:
#   friends: false
smart_menu:
  innerArchive: '文章'
  category: '分类'
  friends: '友链'
  aboutme: '关于'
  

friends:
  友情链接1: https://bujige.net
  友情链接2: http://localhost:4000/
  友情链接3: http://localhost:4000/
  友情链接4: http://localhost:4000/
  友情链接5: http://localhost:4000/
  友情链接6: http://localhost:4000/

aboutme: 把人生的全部，<br>奉献给我所热爱的一切。<br><br>谢谢大家 ~


# -———————— 以下为 Yulia 添加的自定义功能 —————————


# 开启百度站长平台自动推送，有利于 SEO 搜索（https://ziyuan.baidu.com/linksubmit/index）
baidu_push_auto: false
  
# 文章版权说明：默认开启，关闭将 enable 设置为 false。
post_copyright:
  enable: true
  # 版权协议名称
  license: CC BY-NC-SA 3.0
  # 版权协议地址
  license_url: https://creativecommons.org/licenses/by-nc-sa/3.0/
  
# 网站访问量统计：访客人数统计、访问次数统计。
site_count:
  # enable 设置为 false 时不显示网站访问统计。
  enable: false
  # 网站访客人数统计设置
  site_uv: true
  site_uv_header: <i class="icon-user icon"></i> 本站访客数
  site_uv_footer: 人
  # 网站访问次数统计设置
  site_pv: true
  site_pv_header: <i class="icon-eye icon"></i> 本站总访问量
  site_pv_footer: 次
  
  
# 文章页阅读统计：字数统计、阅读时长、访问次数
page_read_count:
  # enable 置为 false 不显示阅读相关统计。
  enable: true
  # 文章字数统计
  word_count: true
  word_count_header: <i class="icon-statistics icon"></i> 字数统计：
  word_count_footer: 字
  # 文章最低阅读时间
  read_time: true
  read_time_header: <i class="icon-book icon"></i> 阅读时长 ≈
  read_time_footer: 分
  # 文章页访问次数统计设置
  page_pv: true
  page_pv_header: <i class="icon-eye icon"></i> 阅读数：
  page_pv_footer: 次

# 页面点击小红心
clickLove:
  # 关闭请设置为 false
  enable: true
  
# 悬停预览图片效果
hover_effect:
  # 'global' 0: 分开设置; 1: 全局启用, 2: 全局关闭
  global: 1
  # subNav - 导航栏悬停预览图片效果
  subNav: true
  
# 页面加载进度条 | progressBar
# Demo: http://github.hubspot.com/pace/docs/welcome/
# type: barber-shop|big-counter|bounce|center-atom|center-circle|
#       center-radar|center-simple|corner-indicator|flash|flat-top|
#       loading-bar|mac-osx|minimal
# color: black|blue|green|orange|pink|purple|red|silver|white|yellow|
progressBar:
  enable: false
  type: 'minimal'  # Keep Quotes | 注意保留引号
  color: blue
  
# 底部
footer:
# 网站成立年份,置为 false 则默认显示今年（显示格式为：© 2018-2020）
  since: 2018
# 网站版权信息说明，置为 false 则默认显示作者或网站标题
  copyright: false
# 网站备案号，置为 false 则不显示（显示格式为：© XXXICP备XXXX号）
  icp: XXXICP备XXXX号
